### ISSUE TITLE
graphmap installation problem

### ISSUE THREAD

**Issue by Cynthia0411** [isovic/graphmap#106]
when I make Graphmap, it warn me with this error: fatal error: sequences/single_sequence.h: No such file or directory
 #include "sequences/single_sequence.h"
How should I do to install the software package?

**Comment by isovic** [comment]
Hi, you need to clone the repository recursively to pull all the submodules:
```
git clone --recursive https://github.com/isovic/graphmap
cd graphmap
make
```
Best regards,
Ivan.
