### ISSUE TITLE
Support BAM as input

### ISSUE THREAD

**Issue by andreas-wilm** [isovic/graphmap#15]
Would be nice if Graphmap would support read input from BAM files, with the option to retain existing tags like insertion and deletion qualities for example. Also, the new SMRT Portal / Pacbio versions will produce BAM as native sequencing output apparently.

**Comment by isovic** [comment]
The latest release (v0.3.0) supports reading sequences from SAM and GFA files. Hope this will do for now? :-)

Ivan

**Comment by andreas-wilm** [comment]
Where's the thumbs up icon?
