### ISSUE TITLE
Mac fails build under OS X El Capitan g++-5.3.0

### ISSUE THREAD

**Issue by pfaucon** [isovic/graphmap#22]
There seems to be a build error when building on mac.  There are a number of files that seem to #include "sequences/single_sequence.h" but searching the repository I don't find any file names single_sequence.h.  I tried removing those references which leads to more missing headers down the lines, utility/* and seqan/*, which in turn lead to build errors from missing the debug commands.

The error given is:
> make mac
> mkdir -p obj_mac/src/alignment/
> /usr/local/bin/g++-5 -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/"  -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_mac/src/alignment/alignment.o src/alignment/alignment.cc
> In file included from src/alignment/alignment.cc:8:0:
> ./src/alignment/alignment.h:19:39: fatal error: sequences/single_sequence.h: No such file or directory
> compilation terminated.
> make: *** [obj_mac/src/alignment/alignment.o] Error 1

g++ output:
> /usr/local/bin/g++-5 -v
> Using built-in specs.
> COLLECT_GCC=/usr/local/bin/g++-5
> COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.3.0/libexec/gcc/x86_64-apple-darwin15.0.0/5.3.0/lto-wrapper
> Target: x86_64-apple-darwin15.0.0
> Configured with: ../configure --build=x86_64-apple-darwin15.0.0 --prefix=/usr/local/Cellar/gcc/5.3.0 --libdir=/usr/local/Cellar/gcc/5.3.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.3.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib
> Thread model: posix
> gcc version 5.3.0 (Homebrew gcc 5.3.0)

**Comment by pfaucon** [comment]
User error, I thought I had run 'make modules' but I had not.

**Comment by isovic** [comment]
Hi,
I'm glad to hear things worked out!

Ivan
