### ISSUE TITLE
Presets stopped working

### ISSUE THREAD

**Issue by andreas-wilm** [isovic/graphmap#28]
Presets (e.g. -x illumina) translate into option -w which was removed:

    graphmap align -x illumina ...
    ERROR: Unknown parameter '-w'.

Andreas

PS:  version 0.3.0 commit 1d16f07

**Comment by andreas-wilm** [comment]
Just replacing '-x illumina' with 'align' gives *very* different results. I have 16S sequences that do not match anything in a huge database with 0.3.0 as opposed to 0.2.2

**Comment by isovic** [comment]
Hi Andreas, thanks for the report!
I'll get to it soon - my time-clench is finally subsiding.

**Comment by andreas-wilm** [comment]
Cool. For my reference: https://github.com/CSB5/GERMS_16S_pipeline/issues/14

**Comment by isovic** [comment]
Hi Andreas,
this should be resolved now in the newest release.
Try ```git pull; make modules; make```.
Thanks for reporting this!
Best regards,
Ivan.
