### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by noncodo** [isovic/graphmap#29]
I'm getting the following error (gcc-4.8) on a Mac: 
ld: warning: directory not found for option '-Lcodebase/seqlib/src/libs/libdivsufsort-2.0.1/build/lib'
Should it be ? : codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/

**Comment by andreas-wilm** [comment]
Hey Martino,

Sorry, I can't reproduce this. Which commit are you using? Did you run a `make clean` first by any chance? And, did you use an extra option to `make`?

Thanks,
Andreas

**Comment by isovic** [comment]
Hi Martino,
any progress on this?
Just in case this isn't resolved, before running ```make``` run ```make modules``` to fetch all the submodules required by the repo.
Best regards,
Ivan.
