### ISSUE TITLE
Cannot build reference index

### ISSUE THREAD

**Issue by samhunter** [isovic/graphmap#32]
I am attempting to test graphmap using some human reads we just generated with a Minion. 

I cloned and compiled the software as per the instructions and should be running the latest version in the master branch:
Version: v0.3.0
Build date: Aug 11 2016 at 17:06:03

I also downloaded the latest human genome build ( GCA_000001405.23_GRCh38.p8_genomic.fna from the GRC -- ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA_000001405.23_GRCh38.p8).

I tried to map and just build the index with no success:

1) Build and map in 1 command:
$ graphmap align -K fasta -r /grc/genomes_db/GCA_000001405.23_GRCh38.p8_genomic.fna -d gt50k.fasta -o test.sam
[17:27:37 Index] Running in normal (parsimonious) mode. Only one index will be used.
[17:27:37 Index] Index is not prebuilt. Generating index.
[17:27:37 LoadOrGenerate] Started generating new index from file '/grc/genomes_db/GCA_000001405.23_GRCh38.p8_genomic.fna'...
[Fri, 12 Aug 16 00:27:37 +0000 FATAL] #5: Unexpected value found! Input sequence file format unknown!
In function: 'LoadSeqs_'.

[Fri, 12 Aug 16 00:27:37 +0000 FATAL] #5: Unexpected value found! Input sequence file format unknown!
In function: 'LoadSeqs_'.
Exiting.

2) Try to build index only as per the documentation:
$ graphmap align -I -r GCA_000001405.23_GRCh38.p8_genomic.fna 
Reads file does not exist: ''

For detailed help, please run with -h option.

Example usage:
  ./graphmap align -r escherichia_coli.fa -d reads.fastq -o alignments.sam

GraphMap (c) by Ivan Sovic, Mile Sikic and Niranjan Nagarajan
GraphMap is licensed under The MIT License.

Version: v0.3.0
Build date: Aug 11 2016 at 17:06:04

**Comment by isovic** [comment]
Hi,
I will have to inspect this, but currently the servers are down for the next week or so because of holidays.
Could you try renaming your extension from 'fna' to 'fa' and re-running the first attempt?
Let me know how it goes.

Best regards,
Ivan.

**Comment by samhunter** [comment]
Thanks for the suggestion Ivan, creating a symlink with a ".fa" extension fixed the problem!

Sam

**Comment by isovic** [comment]
Ok, good to know. I'll leave this issue open until I resolve the problem - this shouldn't be happening.
Thanks again!
