### ISSUE TITLE
Empty lines in Sam file

### ISSUE THREAD

**Issue by mjpdejong** [isovic/graphmap#33]
Graphmap alignment resulted in a Sam-file containing emtpy lines. Downstream applications like samtools gave me errors because of this.

Case - Aligning of a 1D NanoPore E.Coli dataset to the reference genome

```
graphmap align \
        -t 32 \
        -C \
        -r U00096.2.fasta \
        -d $inputfile \
        -o /mnt/output/output.sam
```

Workaround I used, but not ideal:
`sed '/^$/d' output.sam > output.new.sam`

**Comment by isovic** [comment]
Hi, thank you for reporting this!
It should be fixed now.
Best regards,
Ivan.
