### ISSUE TITLE
installation on i386?

### ISSUE THREAD

**Issue by rahimrajwani** [isovic/graphmap#35]
My compilation gets terminated with : /usr/include/zlib.h:34:19: fatal error: zconf.h: No such file or directory
 #include "zconf.h"

My guess is it is because I am compiling on i386 system.

Do you have any advice to fix this?

Thanks in advance.

**Comment by andreas-wilm** [comment]
Hi,

If zlib.h is there zconf.h should be there as well. Is this a very old
system you're on?
What's the zlib-dev version?
You might want to check
http://stackoverflow.com/questions/35308535/having-errors-when-trying-to-compile-these-files-zconf-missing

Andreas

**Comment by isovic** [comment]
Hi,
Did you manage to get it working?
In any case, GraphMap is designed for 64-bit platforms and we never tested it on a 32-bit one, so I would advise to try switching to a compatible system.
Best regards,
Ivan.

**Comment by rahimrajwani** [comment]
Hi Ivan,

Thanks for your msg.

No, I couldn't get it working so I gave up on it. At the moment, I only
have access to this 32-bit system. But you are right it would be easier if
shift to a 64-bit system.

Many thanks.
