### ISSUE TITLE
avoid copying of stringstreams to determine its length

### ISSUE THREAD

**Issue by tolot27** [isovic/graphmap#37]
For example in line: https://github.com/isovic/graphmap/blob/master/src/graphmap/process_read.cc#L522
`ss.str()` makes a copy of the whole string just to determine its length. I this case, `ss.tellp() > 0` should be sufficient.

**Comment by isovic** [comment]
That's a good catch, thanks!
I'll incorporate it in the next release.

Best regards,
Ivan.

**Comment by isovic** [comment]
Hi, the suggestion has now been implemented in all such occurrences (only a couple though). Thanks again!
