### ISSUE TITLE
ERROR: Unknown parameter '-w'.

### ISSUE THREAD

**Issue by evolgenomology** [isovic/graphmap#38]
Hi, 

when trying to run the program like this
`bin/Linux-x64/graphmap align -x illumina -r /data1/Xenoturbella/redundans/run7-j3-i3/PacBio_scaffolder_results_l7/PacBio_l7.run7-j3-i3.scaffolds.fna.fa -d /data1/Xenoturbella/xenoturbella.TSLR.fastq -o /data1/Xenoturbella/redundans/run7-j3-i3/PacBio_scaffolder_results_l7/xenoturbella.TSLR.graphmap.alignments.sam`

I get
`ERROR: Unknown parameter '-w'.`.

But there is no "w".

Best

Philipp

**Comment by isovic** [comment]
Hi Philipp, thanks for reporting this!
The issue should now be fixed, try ```git pull; make modules; make```.
Best regards,
Ivan.

**Comment by evolgenomology** [comment]
Thanks! Sent with SolMail App--------- Original Message ---------
From: Ivan Sovic 
To: isovic/graphmap 
Date: Wed Oct 12 12:06:18 GMT+02:00 2016
Subject: Re: [isovic/graphmap] ERROR: Unknown parameter '-w'. (#38)

Hi Philipp, thanks for reporting this!
The issue should now be fixed, try git pull; make modules; make.
Best regards,
Ivan.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/isovic/graphmap","title":"isovic/graphmap","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/isovic/graphmap"}},"updates":{"snippets":[{"icon":"PERSON","message":"@isovic in #38: Hi Philipp, thanks for reporting this!\r\nThe issue should now be fixed, try ```git pull; make modules; make```.\r\nBest regards,\r\nIvan."}],"action":{"name":"View Issue","url":"https://github.com/isovic/graphmap/issues/38#issuecomment-253172458"}}}
