### ISSUE TITLE
Compilation error mac

### ISSUE THREAD

**Issue by mbhall88** [isovic/graphmap#39]
Getting this error when running `make mac`
`ld: warning: directory not found for option '-Lcodebase/seqlib/src/libs/libdivsufsort-2.0.1/build/lib`

It looks like this isn't actually a folder (I guess the error is saying that already). Is it supposed to be `libdivsufsort-2.0.1-64bit/` perhaps?

**Comment by isovic** [comment]
Hi Michael,
before compiling, did you run ```make modules```?
This will initialize all required submodules.
Best regards,
Ivan.

**Comment by mbhall88** [comment]
Hi Ivan,
Yes I ran the following commands immediately prior:
`git clone https://github.com/isovic/graphmap.git`  
`cd graphmap `
`make modules` 
`make mac`
In that exact order.
Kind Regards,
Michael

**Comment by isovic** [comment]
Oh, I see, it's a leftover from an older version, before I trimmed down libdivsufsort.
Can you try a ```git pull``` now and let me know?
Thanks!
Best regards,
Ivan.

**Comment by mbhall88** [comment]
Ok, thought it might have been something like that. Ill give it a go in the morning and let you know how I go.

King Regards,
Michael

**Comment by mbhall88** [comment]
Excellent. Works fine now.
Thanks for that.
Kind Regards,
Michael
