### ISSUE TITLE
Extended CIGAR (sam v.1.4)

### ISSUE THREAD

**Issue by aechchiki** [isovic/graphmap#40]
Hi Ivan, 

I wonder if there is a way to obtain an extended CIGAR string in the sam output by the current version of Graphmap, aka displaying detailed (X,=) for (match,mismatch) instead of M for alignment match (that can be match or mismatch). 

Thanks in advance, 
Amina

**Comment by isovic** [comment]
Hi Amina!
Sure, there is an option ```--extcigar``` that does this.
Hope this helps,
Best regards,
Ivan.

**Comment by aechchiki** [comment]
Many thanks, that's exactly what I was looking for. 

Cheers, 
Amina
