### ISSUE TITLE
extra newline

### ISSUE THREAD

**Issue by citizenlee** [isovic/graphmap#42]
Hi,
I've been able to align using:

Linux-x64/graphmap align -C -r genome.fa -d 1Dreads.fastq -o chr.sam

However, when I try to create a sorted bam file, I receive "parse error at line X" messages. Going into the sam file, it looks like there are empty new lines between samlines. 

Possibly an error in the code that inserts this during output?

**Comment by citizenlee** [comment]
I can confirm that removal of the empty new lines as such:

awk 'NF' file.sam > file.cleaned.sam 

will allow samtools to sort and generate the bam files.

**Comment by isovic** [comment]
Hi!
Which commit are you currently using?
There was a recent Issue #33 which reported the same thing. It should be resolved now, but please do let me know if you have the most recent commit and whether it works so that I can inspect in detail.

Thank you for reporting this!
Best regards,
Ivan.

**Comment by citizenlee** [comment]
Hi Ivan,
I am on commit 817ba03fc19e0fb2076381eb9536ff99240bd468. This should be the
latest version - I just pulled it off git earlier this week.

Let me know how else I can help.

Regards,

Henry

**Comment by isovic** [comment]
Hi,

Indeed there were empty lines when circular alignment was used. This has been fixed for months now, so I'm closing the issue.

Best regards,
Ivan.
