### ISSUE TITLE
GOMP_4.0 not found

### ISSUE THREAD

**Issue by wzylin** [isovic/graphmap#45]
Hi,
I encounter an problem when I run the graphmap for alignment:
graphmap: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by graphmap)

I compiled the graphmap using gcc-6.2.0 which install at home/user directory. The default version of gcc on my server is 4.6.
Is there any way to redirect the graphmap to find the libgomp.so.1 from other directory? or how can I solve this problem?

Thank you!

**Comment by andreas-wilm** [comment]
Hi Wzylin,

please try adding the GCC library (lib or lib64) directory to your LD_LIBRARY_PATH, i.e. export LD_LIBRARY_PATH=$HOME/your-path-to-gcc-6.2/lib:$LD_LIBRARY_PATH

Andreas

**Comment by wzylin** [comment]
Dear Andreas,
Thank you for your kind help.
Problem solved!

**Comment by tiagobrc** [comment]
This solved my problem as well! Thanks.
