### ISSUE TITLE
installation problem on debian 8 (jessie)

### ISSUE THREAD

**Issue by miles-gene** [isovic/graphmap#46]
Hello
I'm new to linux and I'm having problems compiling graphmap i think. My linux distro is using gcc 4.9 so after downloading the source files I ran $make modlues and then $make without specifying which version of gcc to use unlike in the INSTALL.md file.  There was a lot of activity on the screen. Subsequently $graphmap command was  not recognised and no green folders were created anywhere I'd expect. Perhaps I am missing some dependancies. Any advise would be greatly appreciated

**Comment by isovic** [comment]
Hi,
So, after running make, the folder bin/ does not exist? The binary should be located at bin/Linux-x64/graphmap.
Perhaps there are some dependencies missing.
Could you by any chance do a fresh git clone, and run the following:
```  
make modules 2>&1 | tee makemodules.log  
make 2>&1 | tee make.log  
```  
And attach these two files (```makemodules.log``` and ```make.log```) here so I can take a look?

Best regards,
Ivan.

**Comment by miles-gene** [comment]
Hi
Thanks for your reply. I have generated the logfiles but can't attach them 'we don't support that file type' error. I have so far been unable to save/convert them to a supported file type or export them in other formats but I'll get there.
There was data in /bin/Linux-x64/graphmap after compiling the previous clone.

thanks again

**Comment by isovic** [comment]
Hi,
yeah, forgot about that. You can rename the extension to these files from .log to .txt, or rerun everything as such:
 ```  
make modules 2>&1 | tee makemodules.txt  
make 2>&1 | tee make.txt  
```
Another option is to zip the files and upload them here.
Best regards,
Ivan.

**Comment by miles-gene** [comment]
Hi Ivan
[makemodulestext.txt](https://github.com/isovic/graphmap/files/659603/makemodulestext.txt)
[maketext.txt](https://github.com/isovic/graphmap/files/659602/maketext.txt)

I hope these are ok. 
Miles

**Comment by isovic** [comment]
Hi Miles,
from what I can tell, the compilation went fine and you should have a binary at the relative path: bin/Linux-x64/graphmap .
What output do you get when you try to run it?
Best regards,
Ivan.

**Comment by miles-gene** [comment]
Hi Ivan
bash: graphmap: command not found

I haven't added anything to 'my path' or edited any bashrc files which I have been reading about. I don't know if that's relevant. Thanks for looking at the logs
Miles

**Comment by miles-gene** [comment]
Hi again
If I go to the Linux-x64 directory ./graphmap works! Sorry for bothering you, the previous package I installed (poretools) worked from any directory.
thanks for your help

**Comment by isovic** [comment]
Oh, I see!
Yup, this is the default behavior on Linux unless you either copy the binary to the /usr/bin/ folder or otherwise provide the system with a path to your binary.

You can install graphmap in the /usr/bin/ folder simply using the Makefile but you will need sudo access (this often works on many other packages too, but depends on the developers though). When you're in the graphmap folder, run:  
```sudo make install``` 
This will automatically copy the binary to ```/usr/bin/``` so that you can run it directly without specifying the path.

I'm happy to hear it worked!
Best regards,
Ivan.

**Comment by miles-gene** [comment]
Hi Ivan
Thanks for the Linux tips, I'm on a learning curve as they say.  Graphmap worked great for mapping/overlapping the lambda reads I generated, I will now use it to help assemble some BACs.

happy new year
Miles

**Comment by isovic** [comment]
No worries, Linux can be a huge chunk to bite, just hang on :-)

Happy new year to you to!
Ivan
