### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by wzylin** [isovic/graphmap#47]
Hi,
Graphmap would sometimes be terminated before finished. 
I dont know what was going on there.
Could you help to check? Thank you!

error message
....
....
1 (35.33%) [m: 38765, u: 4570], length = 4567, qname: d2055667-23e2-4a2f-9f31-15[22:09:37 ProcessReads] [CPU time: 16923.34 sec, RSS: 3080 MB] Read: 43355/122701 (35.33%) [m: 38774, u: 4570], length = 15346, qname: d8bdb47f-cc9a-4769-b9bb-1.../var/spool/torque/mom_priv/jobs/487788.statgenpro.SC: line 10: 11686 Segmentation fault      (core dumped) graphmap align -t 12 -r C.elegans_ref.fasta -d allreads_ac.correctedReads.fasta.gz -o all_ac2w.sam

**Comment by mdcao** [comment]
I ran into the same problem too.

**Comment by isovic** [comment]
Hi wzylin,
I would very much like to inspect this in detail, could you by any chance share the read which causes this?

You can try re-running the process in one thread with -t 1, in this case when program segfaults the qname shown in terminal will be the last one that was supposed to have been processed but failed.
Could you extract this read into a separate file, and try mapping only this read to check whether it breaks as expected.
If it does, could you send it to me for further inspection?

Thank you,
Best regards,
Ivan.

**Comment by isovic** [comment]
Also, which commit are you using?

Ivan

**Comment by wzylin** [comment]
this problem seems solved when I update the graphmap to 0.3.2.
Will let you know when the problem comes up again.
