### ISSUE TITLE
Sam header when mapping to transcriptome

### ISSUE THREAD

**Issue by wdecoster** [isovic/graphmap#51]
I tried mapping to the transcriptome, and it seems to have worked. However, while the reads are mapped to the individual chromosomes, the sam header still consists of the transcript IDs.
Example:

```
@HD     VN:1.0  SO:unknown
@SQ     SN:ENST00000456328_1    LN:1657
@SQ     SN:ENST00000515242_1    LN:1653
@SQ     SN:ENST00000518655_1    LN:1483
@SQ     SN:ENST00000450305_1    LN:632
@SQ     SN:ENST00000438504_1    LN:1783
```

Since the reads have the expected "chromosome" identifiers in the sam fields, this results in many error messages such as printed below when converting the sam file to bam or calling samtools flagstat:

`[W::sam_parse1] urecognized reference name; treated as unmapped`

**Comment by isovic** [comment]
Hi,
Ugh, I missed that one.
I'll fix it soon and let you know.
Thank you for the report!
Best regards,
Ivan.

**Comment by isovic** [comment]
Sorry it took a bit...
Could you try pulling the latest commit and giving it a spin?

Best regards,
Ivan.

**Comment by wdecoster** [comment]
Sam/bam files are okay now! Alignment looks fine. I'm going to rerun with some trimming at the end of the reads, I get the idea that for many reads the end of read is softclipped because of lesser quality at end of sequences/adapter sequence.

**Comment by citizenlee** [comment]
I seem to be having this similar error with genome alignment. 

Getting many lines with:
[sam_read1] reference 'U00096.2' is recognized as '*'.
