### ISSUE TITLE
Crashing with -C circular reference parameter

### ISSUE THREAD

**Issue by photocyte** [isovic/graphmap#52]
Hi there,

I am using graphmap commit 84f058f92dc5be02022e944dd1d6b9414476432a to map a set of PacBio RSII reads to circular mitochondrial genomes from NCBI (for partitioning and subassembly of mitochondria from a somewhat dirty sample of a wildcaught specimen).

With the following invocation, graphmap crashes almost immediately:
`/lab/solexa_weng/testtube/graphmap_main/bin/Linux-x64/graphmap align -r head3_mito_reference.fasta -C -d head3_reads.fasta -P -o test.sam`

However without the -C parameter the mapping works fine.  I've attached the minimal set of data needed to make graphmap crash (3 mitochondrial genomes, and 3 reads), as well as the log from the crashed run.

I've also tried with the most recent commit of the "dev" branch, however it still crashes.

Thank you for your work on graphmap!

[graphmap_circular_crash.zip](https://github.com/isovic/graphmap/files/760683/graphmap_circular_crash.zip)

**Comment by filicado** [comment]
same here

**Comment by isovic** [comment]
Hi all,
thank you for reporting this and for your patience!
This issue will be fixed in the next release which is coming soon (within a week, hopefully), together with some new goodies such as speed improvements.
Best regards,
Ivan.
