### ISSUE TITLE
segmentation fault when using reference with ambiguous characters

### ISSUE THREAD

**Issue by filicado** [isovic/graphmap#54]
So I managed to make this reproducible and am happy to share the fastq and reference files and scripts.

It doesn't happen with every ambiguous reference and the error isn't always the same.

**Comment by isovic** [comment]
That would be great!
Can you upload them here (if they are not big?) or email me a download link?

Or - could you test the latest commit to see if it's still happening?

Thank you!
Best regards,
Ivan.

**Comment by filicado** [comment]
I will try the latest commit soon. In the meantime I found a simple hack-fix. Adding a single N as the first base of the reference prevents the crash.

**Comment by isovic** [comment]
Hmm interesting hack :D
Not quite sure why it works :D

**Comment by filicado** [comment]
problem no longer there in the new build, closing.
keep up the good work, graphmap is a great tool in our hands!

**Comment by isovic** [comment]
Thank you very much! :-)

Best regards,
Ivan.
