### ISSUE TITLE
Sam header

### ISSUE THREAD

**Issue by citizenlee** [isovic/graphmap#56]
Seems to be an issue with sam headers with commit a697f01.

While converting sam -> bam, receiving many lines of:
[sam_read1] reference 'U00096.2' is recognized as '*'.

This did not pop up when using the same fastq data for alignment on commit 817ba03.

**Comment by isovic** [comment]
You're right - forgot to trim the sequence headers to first space in the new index. Pushed a fix to master, can you test now?

Best regards,
Ivan.

**Comment by citizenlee** [comment]
Works. Thanks very much, Ivan!
