### ISSUE TITLE
Core Dumped - v0.5.0

### ISSUE THREAD

**Issue by Nilad** [isovic/graphmap#57]
Hi, i run graphmap with a fresh clone of your github (today) and i have this core dump. I work with others mappers with the same file for genome reference and fastq.

Cmd line :
> graphmap align -t 8 -r mygenome.fasta -d myFastq.fastq -o myOutput.sam

Error :
> [09:24:46 BuildIndexes] Loading reference sequences.
> [09:25:21 SetupIndex_] Building the index for shape: '11110111101111'.
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted (core dumped)

If you need complementary information, i am at your disposition.

**Comment by isovic** [comment]
Hi,
how big is your reference, and how much RAM does your machine have?
Currently, building the index peaks at 32x reference_size (in bytes), but this will be reduced significantly in the next release.

Best regards,
Ivan.

**Comment by Nilad** [comment]
I have 48Go of RAM for a genome reference of 2.6Go.

**Comment by isovic** [comment]
Unfortunately that won't be enough to build the index...do you have access to a higher-mem machine where you could build the index and transfer locally? Once build, the index will consume only about ~20GB.
This will be patched up in the next release.

Best regards,
Ivan.

**Comment by Nilad** [comment]
Thank you for your support.

I launch on an another machine (177Go RAM), it's take 90Go of RAM. 
I hope you can optimize the RAM cost of graphmap soon.
