### ISSUE TITLE
SAM problem - v0.5.0

### ISSUE THREAD

**Issue by Nilad** [isovic/graphmap#58]
I have this kind of error with samtools :

`[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Erreur de segmentation (core dumped)
`
I try with an another tool for quality report of the SAM who give me only the 3 first line of the SAM.

Maybe you have a problem with your SAM file generator.

I am at your disposition for complementary information.

**Comment by Nilad** [comment]
Resolved.

**Comment by isovic** [comment]
Hi,
I'm wondering how you resolved the issue? :-)

Best regards,
Ivan.

**Comment by Nilad** [comment]
I just miss a line command in my script.
