### ISSUE TITLE
Fix building with gcc 5

### ISSUE THREAD

**Issue by jpecar** [isovic/graphmap#59]
While building racon I noticed this:

src/graphmap/region_selection.cc:177:56: error: ‘floor’ is not a member of ‘std’
   float min_allowed_bin_value = std::max(2.0f, (float) std::floor(parameters->min_bin_percent * max_bin_value));

Looks like include <cmath> is missing somewhere.

**Comment by isovic** [comment]
Hi,

Thank you for the report!
I now added the include for cmath.

Btw. You can build racon without running `make tools`. That one is useful for validating the tests.

Best regards,
Ivan.
