### ISSUE TITLE
 output unmapped reads

### ISSUE THREAD

**Issue by mictadlo** [isovic/graphmap#65]
Hi
Does GraphMap output unmapped reads, because I try to remove contamination from PacBio reads?

Thank you in advance.

Micha

**Comment by isovic** [comment]
Hi Micha,

Yes - for every read in the input dataset, GraphMap will generate at least one output alignment line. If a read was not successfully mapped, it will be reported as unmapped via the SAM flag (value equal to `4`).

Best regards,
Ivan.

**Comment by mictadlo** [comment]
Thank you
