### ISSUE TITLE
Turn terminal deletions into soft clips

### ISSUE THREAD

**Issue by andreas-wilm** [isovic/graphmap#7]
I got a bunch of sequences that get aligned with leading (trailing not observed) deletions e.g. 50D740M1D1M1D2M. Terminal indels don't make sense in an alignment (after all: how do you distinguish between a terminal insertion or deletion?). They should be soft clipped.

**Comment by isovic** [comment]
That's strange, I thought I had handled this. What parameters are you running GraphMap on?

**Comment by andreas-wilm** [comment]
graphmap  -x  illumina

on the previously mentioned 16S database using the official v0.21 and commit e45f9de

**Comment by andreas-wilm** [comment]
Here's an example sequence:
ACTCCTACGGGAGGCAGCAGTAGGGAATCTTCCGCAATGGACGAAAGTCTGACGGAGCAACGCCGCGTGAGTGATGAAGGCTTTCGGGTCGTAAAACTCTGTTGTTAGGGAAGAACAAGTGCTAGTTGAATAAGCTGGCACCTTGACGGTACCTAACCAGAAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGCGCGCAGGTGGTTTCTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGAAACTTGAGTGCAGAAGAGGAAAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGAGATATGGAGGAACACCAGTGGCGAAGGCGACTTTCTGGTCTGTAACTGACACTGAGGCGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTAGGGGTTGGGGCCTTTGAGGCTTTAGTGGCGCAGCTAACGCGATAAGTAGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCTGGTCTTGACATCCACGGAAGTTTTCAGAGATGAGAATGTGCCTTCGGGAACCGTGAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGCTG
which matches sequence 4453932	with cigar string	50D308M1D114M1I86M1D38M1D9M1I21M1I101M1D8M1I48M1D1M1D2M

**Comment by andreas-wilm** [comment]
Fixed in dev 604a386. Shall we keep this open until dev is merged on master?

**Comment by andreas-wilm** [comment]
Merged already? :)

**Comment by isovic** [comment]
Merged :P
