### ISSUE TITLE
Conda thinks 0.22.1 is the most recent version

### ISSUE THREAD

**Issue by eyesmo** [isovic/graphmap#75]
When I installed graphmap with
`conda install graphmap`
it downloads version 0.22.1, rather than the most up-to-date version 0.5.2.
Additionally, for reasons unclear I couldn't jump straight to installing 0.5.2 with
`conda install graphmap=0.5.2`
because conda couldn't find 0.5.2. However, if I try
`conda install graphmap=0.4.0`
conda asks me if I'm sure I want to downgrade the software (y), and then installs version 0.4.0.
And once 0.4.0 is installed, 
`conda install graphmap=0.5.2`
works, and I can install the latest version
I think conda assumes that 0.22.1 comes after 0.5.2 numerically. Just a heads up!

Screenshots attached below in order of issue/resolution.
<img width="495" alt="screen shot 2017-08-08 at 12 43 10 pm" src="https://user-images.githubusercontent.com/2289040/29086317-cebf8fae-7c37-11e7-935f-b4d7acffdbff.png">
<img width="431" alt="screen shot 2017-08-08 at 12 44 36 pm" src="https://user-images.githubusercontent.com/2289040/29086334-dc2517ae-7c37-11e7-9d3b-04f5c5afbf11.png">
<img width="570" alt="screen shot 2017-08-08 at 12 45 42 pm" src="https://user-images.githubusercontent.com/2289040/29086344-e494effe-7c37-11e7-851c-fe51e5ebb47f.png">
<img width="569" alt="screen shot 2017-08-08 at 12 45 56 pm" src="https://user-images.githubusercontent.com/2289040/29086352-ef226b18-7c37-11e7-91c6-55945217e25f.png">
<img width="493" alt="screen shot 2017-08-08 at 12 46 27 pm" src="https://user-images.githubusercontent.com/2289040/29086363-f6da5f96-7c37-11e7-9095-e53589457a23.png">

**Comment by wdecoster** [comment]
What if you specify the channel explicitly:
```bash
conda install graphmap=0.5.2 -c bioconda
```

This works for me.

0.22 is older but more recent in "version numbering" so understandable that conda selects the wrong version...

**Comment by isovic** [comment]
Hi,
Thank you both for reporting and resolving this!
Several versions ago we decided on changing the versioning convention to the commonly used `major.minor.patch` format which we liked more for the long-term development. Unfortunately this had an effect as the one described above, but it will enable more flexibility in the long run.
Best regards,
Ivan.
