### ISSUE TITLE
Typo in parameter option help menu

### ISSUE THREAD

**Issue by lennythomas** [isovic/graphmap#8]
In the options you state `-F` is for parsimonious memory mode.

https://github.com/isovic/graphmap/blob/master/src/utility/program_parameters.cc#L616

I think you mean `-P`

https://github.com/isovic/graphmap/blob/master/src/utility/program_parameters.cc#L56

**Comment by isovic** [comment]
That's a nicely spotted mistake, thank you!
It will be fixed in the next relese - until then I'll leave this issue open to remind me.

**Comment by isovic** [comment]
Merged with master.
